// <auto-generated />
namespace GeneralStoreAPI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class TranactionfixDatTime : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TranactionfixDatTime));
        
        string IMigrationMetadata.Id
        {
            get { return "202108102216520_Tranaction fix DatTime"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
